### ISSUE TITLE
error handling - 10.13.3 asr warning behavior shows as error?

### ISSUE THREAD

**Issue by arubdesu** [google/restor#15]
Hi from 🇯🇵 ! I'm seeing this when it appears to otherwise have been successful:
<img width="649" alt="screenshot 2018-01-30 16 19 54" src="https://user-images.githubusercontent.com/388808/35553228-56d0a938-05da-11e8-974d-65d83123e6d3.png">
Do we want to refer to this as a 'warning' instead of an error? Thanks!

**Comment by tburgin** [comment]
Ahoy! For APFS source images I believe this is an error. I have not tested with an hfs source volume...
And this is not on the iMac Pro, yes? Because you will get that error even when using an APFS source image. Though, that's another can of worms that we may try and address.

**Comment by arubdesu** [comment]
This is Restor running _on_ an iMacPro, pushing an HFS image _to_ a non-touchbar mac, so strictly speaking no personalization is required, I'd think? That's why I like the notice bubbling up somewhere, but in this case action isn't actually required - it's possible techs will interpret the informational (what I interpret as a) warning as an error. (This is hard enough even when it's spelled out in text that the message is just debug/informational.

**Comment by tburgin** [comment]
Gotcha, we should be able to tackle this when working on the changes proposed in https://github.com/google/restor/issues/16.
