### ISSUE TITLE
Default startup disk is not set when EFI password is enabled

### ISSUE THREAD

**Issue by Coros** [google/restor#17]
I have a MacBook Air that I've been successfully testing restor with.  If I turn on the firmware password, then restore an image, the mac boots to the blinking folder icon.  If I remove the firmware password and run a restore, the mac boots the freshly loaded OS normally.

Not sure if this is a bug, limitation, or needs to be a feature request to support EFI passwords. 

In case it matters: I'm using a 10.13.3 APFS image built with AutoDMG against a 2011 MacBook Air.

**Comment by arubdesu** [comment]
As my experiencing that symptom pre-dates Restor, may I just say my 'fix'/workaround is:
I option-boot the machine post-imaging holding down control, which causes the internal hard drive with the one bootable file system to show a circular arrow below it. Clicking that arrow tells the hardware(nvram?) to look at that volume for a bootable partition from then on.

**Comment by tburgin** [comment]
I believe this is working as intended. But feel free to try [v1.5](https://github.com/google/restor/releases/tag/1.5). We added a bless step when running Restor on macOS 10.13.4+.
