### ISSUE TITLE
Restor shows the Recovery HD when a machine is connected

### ISSUE THREAD

**Issue by jbaker10** [google/restor#2]
When a machine is connected to the machine running Restor, the app will show you two disks. The primary partition (i.e. 250GB) and what appears to be the Recovery HD (650MB). It should only show the primary HD if possible.

See image in the README regarding Disk Choice

**Comment by russellhancox** [comment]
Could you provide the output of `diskutil list` when you have a disk connected? The UI is meant to be filtering out _Recovery HD_ partitions and it's always worked in our testing.

**Comment by jbaker10** [comment]
Sorry, haven't gotten a chance to test this. Will try on Monday and update!

**Comment by jbaker10** [comment]
Was unable to re-create this bug. Upon launching Restor and connecting a machine, only the main volume is shown. Will close the issue now.
