### ISSUE TITLE
Crash while downloading/caching image

### ISSUE THREAD

**Issue by arubdesu** [google/restor#22]
Not sure what's up with it failing several GBs into a download, was assuming it was something to do with 10.13.1 but it's still unhappy on 10.13.3. Crash report attached
[crash.txt](https://github.com/google/restor/files/1766381/crash.txt)

**Comment by tburgin** [comment]
Thanks for the report. Looks like @nguyen-phillip has already fixed this in #21.
Expect a new build soon!

**Comment by arubdesu** [comment]
Confirmed fixed, thanks!
