### ISSUE TITLE
need to bless after restoring 10.13.4 (apfs)

### ISSUE THREAD

**Issue by mjsanders** [google/restor#27]
I use Restor 1.4, and since restoring  10.13.4 (apfs) images created with AutoDMG I noticed two things:
-restor takes much longer (not measured yet)
-after reboot the client, by default it shows blinking question mark (missing bootable volume)

This can be solved in two ways:
-booting using cmd-R to recovery, in Startup Disk set the 'Macintosh HD' to boot volume
-on the mac that runs Restor run this command:` 'sudo bless --folder /Volumes/Macintosh\ HD/System/Library/CoreServices'` (Macintosh HD is the name of the restored volume)

To run this, you first need to mount the just restored volume (with commands like `diskutil mount disk3s1`)
one can check the bootability using `sudo bless --info /Volumes/Macintosh\ HD`. The output can be for a bootable system:
```
          46 => Blessed System File is <Preboot>/BD0ABA49-C7E0-4909-9838-3BE39D5B7B48/System/Library/CoreServices/boot.efi
          44 => Blessed System Folder is <Preboot>/BD0ABA49-C7E0-4909-9838-3BE39D5B7B48/System/Library/CoreServices
The blessed volume in this APFS container is "/Volumes/Macintosh HD"
```
and for a non-bootable volume:

```
           0 => No Blessed System File
           0 => No Blessed System Folder 
```
Can you include the `bless --folder` step into Restor workflow?

**Comment by tburgin** [comment]
Thanks for the report and sorry for the late response. Yes, I will be looking into this and the 10.13.4 ability to restore to the iMacPros.

**Comment by tburgin** [comment]
Give [v1.5](https://github.com/google/restor/releases/tag/1.5) a spin. If you are running Restor from macOS 10.13.4 it should bless the restored system volume.

**Comment by mjsanders** [comment]
Yeah Great, the blessing works (host Mac 10.13.4, Restor 1.5, 10.13.4 apfs.dmg)  Thanks Tom!

**Comment by adinabanea** [comment]
hi, 

i m looking for some answers with my mac pro, my husnand in fact, please help if you can!;) i resset the admin pass of mac pro with comm+R, disk utility/terminal- and after i succed with this issue, i wanted to enter in my account with the new pass- but unfortunately, same time with this ressetting it happen that all my files was totally encrypted in unicide8 type/apfs. from a month already i was trying to restire my husband account but no luck till bow. somebody please help me? ths a lot in advande
