### ISSUE TITLE
Failed to connect to helper tool

### ISSUE THREAD

**Issue by horizontalz** [google/restor#30]
When I launch Restor, I get a "Failed to connect to helper tool"
<img width="601" alt="screen shot 2018-04-17 at 7 58 58 am" src="https://user-images.githubusercontent.com/12464433/38878188-38234d52-4215-11e8-9c6f-1e349ee2ad0c.png">

**Comment by tburgin** [comment]
Try quitting Restor and make sure there are no running instances of `com.google.corp.restord`. A command like `sudo killall com.google.corp.restord` would do the trick. Then try launching Restor again.

If you are still having trouble, you can try deleting the currently installed daemon.
Quit Restor and `sudo rm /Library/PrivilegedHelperTools/com.google.corp.restord`.

**Comment by horizontalz** [comment]
I don't think those tools even downloaded.  Where are these tools originating from?

**Comment by tburgin** [comment]
The helper daemon `com.google.corp.restord` is packaged inside of Restor.app.
It is installed by Restor when your are prompted for your admin credentials.
![screen shot 2018-04-17 at 11 42 27 am](https://user-images.githubusercontent.com/2117646/38880795-8d923aa4-4234-11e8-82aa-dfdab40b74d2.png)

**Comment by horizontalz** [comment]
I do receive that prompt, but when I type in my credentials, it does not seem to install anything.  One thing to note is that I modified the info.plist to disable the App Transport Security policy (my file server does not have https enabled).

**Comment by tburgin** [comment]
Ah, yeah that will do it. Modifying the Info.plist breaks Restor's code signing. Its code signature needs to be intact for the helper tool to be installed successfully.

Luckily Restor is open source. You can make any changes you like and build a version for yourself.
A rough outline:
Clone the source
Add the desired NSAllowsArbitraryLoads keys
Build and Sign

**Comment by tburgin** [comment]
For more context: https://github.com/google/restor/issues/9

**Comment by horizontalz** [comment]
I downloaded the source files and attempted to create a build but it failed.  It seems to missing some files?
![screen shot 2018-04-17 at 3 30 39 pm](https://user-images.githubusercontent.com/12464433/38902180-4ff299b2-4254-11e8-81bb-393ec1ab2469.png)

**Comment by clburlison** [comment]
@horizontalz if you're just trying to add `NSAllowsArbitraryLoads` I'm going to try to maintain a fork with that enabled here https://github.com/clburlison/restor_local_starter_pack. It has my code signing identity. If you have already ran Restor v1.5 you'll need to run `sudo rm /Library/PrivilegedHelperTools/com.google.corp.restord` prior to launching my version.

A rough guideline for how to build from source: 
1. `pod install`
1. You **have** to select a development team for the `Restor` & `com.google.corp.restord` targets inside of Xcode project
1. Update the Makefile to include your Team ID (Line 44)
1. Build via `make google_release`

**Comment by horizontalz** [comment]
Thanks @clburlison!

**Comment by tburgin** [comment]
Nice, thanks @clburlison. You rock!
