### ISSUE TITLE
Infinitely Expanding Window on macOS 10.12.6

### ISSUE THREAD

**Issue by nstrauss** [google/restor#32]
Latest 1.5 release has a GUI bug where main window infinitely expands on launch. Only happens on Sierra 10.12.6. Bug was not present in 1.4. See below link for video. 

https://drive.google.com/file/d/1YGpAvBLZsRlfMwJJwXxhgHz8r9UpX5Ci/view

**Comment by tburgin** [comment]
Oops, we will have someone take care of this tomorrow.

**Comment by tburgin** [comment]
Mind giving https://github.com/google/restor/releases/tag/1.6 a try?

**Comment by nstrauss** [comment]
Fixed in 1.6! Thanks for getting to this so quickly.
