### ISSUE TITLE
Flashing Folder after imaging until USB or Recovery Partition is used

### ISSUE THREAD

**Issue by bhuddleston** [google/restor#36]
We are trying to use the Google tool `restor` and have built an image using the High Sierra Installer + AutoDMG (pulling latest updates).  Once we have deployed the image to the Macbook Pro, the strangest thing happens:  

We get a `Flashing Folder with "?"` until we plugin in a USB drive, then the machine boots fine.  The USB Drive does not have any thing special about it, no bootable partition, no os files, nothing, just formatted HFS+ or AFS.  It will continue like this until we Boot into the Recovery Partition, a) Select the disk and perform First Aid, then b) Select the Boot from this partition.  

This is the only way to get the machine to complete the boot sequence.  Has anyone else seen this?

**Comment by bhuddleston** [comment]
Following some of the data in https://github.com/google/restor/issues/27

We've updated to Restor (v1.6), built an image using AutoDMG upto (10.13.4), but when we restore it, it still needs to either:

Be blessed with `sudo bless --info /Volumes/Macintosh\ HD`
Or Boot into Recovery Console and choose the startup disk

We cannot image a machine without having to fix the boot.

**Comment by tburgin** [comment]
You may have an old version of com.google.corp.restord lingering.

Try deleting it and try again.
sudo rm /Library/PrivilegedHelperTools/com.google.corp.restord

**Comment by bhuddleston** [comment]
That worked! We now are able to image machines without any boot issues.
