### ISSUE TITLE
Allow insecure connections

### ISSUE THREAD

**Issue by ultramizer** [google/restor#38]
There should really be a setting to allow either insecure connections over http, or there should be a way to enable self signed certificates to be accepted. I can not set up a full fledged SSL activated test server just to get thing up and running. It's nice to have SSL active, but in this particular scenario, where you usually use a local subnet webserver to serve the config plist and the image, secure connections are not that important in my opinion.

**Comment by russellhancox** [comment]
If you look at the latest release there's an -insecure version of the release which allows non-HTTPS connections. It is otherwise identical in every way.

**Comment by ultramizer** [comment]
Sorry, didn't check closed issues, and didn't see the release! Thanks!
