### ISSUE TITLE
Is it possible to ignore a disk?

### ISSUE THREAD

**Issue by WardsParadox** [google/restor#42]
We are setting up a restor kiosk that lays down an autodmg image. I was wondering if it's possible to ignore a disk in Restor? We have a 10 TB disk that we are using to take a snapshot of the TDM drive before we wipe and restor it, but restor tries to restor the 10 TB disk :P

**Comment by tburgin** [comment]
We currently only have [hardcoded filters](https://github.com/google/restor/blob/master/Restor/Utilities/DiskFilter.m). A customizable filter would be neat.

@russellhancox came up with the idea of using [NSPredicate](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Predicates/Articles/pSyntax.html#//apple_ref/doc/uid/TP40001795-CJBDBHCB) for generic filtering on the [Disk](https://github.com/google/restor/blob/master/Common/Disk.h) objects.

The defined predicate could be as simple as: `mediaName CONTAINS 'snapshots'`. Or more complex, given all the expressions NSPredicate supports.

Now we just have to build it.
