### ISSUE TITLE
Restor stuck at "Starting..." screen when restoring a new 2018 MacBook Pro.

### ISSUE THREAD

**Issue by samspade21** [google/restor#45]
When using Restor on a MacBook Pro (13-inch, 2018, 4 TBT3) or a MacBook Pro (15-inch, 2018) trying to restore an APFS image (10.13.6 for example), Resor sits at a "Starting..." prompt.  This is using multiple different machines running Restor, all running 10.13.4 or 10.13.6.  Using Disk Utility to blow away the drive and restart does not make a difference.  Happy to send any log files, please let me know which ones would be most beneficial.

**Comment by 1dustindavis** [comment]
I had this same issue (and I am still investigating the cause), but downgrading restor to v1.6 resolved the issue for me.

**Comment by dev-yeet** [comment]
in my experience, if I tried to image it with anything less than 10.13.6 I got this issue..  Only thing that worked for me was to use a build based on 17G2112 build and not the 17G65 Build of 10.13.6. Hopefully this helps

**Comment by tburgin** [comment]
When using v1.7 does the bundled and cached version of the helper tool match?

```
md5 /Applications/Restor.app/Contents/Library/LaunchServices/com.google.corp.restord /Library/PrivilegedHelperTools/com.google.corp.restord
```

If not, or just because, you can try deleting the cached version.
```
sudo rm /Library/PrivilegedHelperTools/com.google.corp.restord
```

**Comment by ghost** [comment]
@tburgin  Above step to remove cached version worked. Using 1.7 was able to:

1. image from 2017 10.13.6 MBP 13 to 2018 10.13.16 MPB 15
2. image from 2018 10.13.6 MBP 15 to 2018 10.13.16 MPB 15
with 10.13.6 17G2112  images. Any images below 10.13.6 fails and 17G65 Build of 10.13.6

Using v1.6 and image 10.13.6 17G65 also did not work

Thanks for the heads up and hope this help on next release

**Comment by lucascantor** [comment]
Completely removing the helper tool solved this stuck at "Starting..." issue for me as well.
