### ISSUE TITLE
Restor will not launch, can't connect to PrivilagedHelperTool

### ISSUE THREAD

**Issue by WardsParadox** [google/restor#49]
Launching Restor results in being unable to be used. Cleared Restor from system (removed /Library/PrivilagedHelperTool/com.google.corp.restord, /Lib/Pref/com.google.corp.restor.plist), re-built and re-ran Restor. The PrivilagedHelperTool does not get copied over. Fails with 
```
default	14:49:14.461610 -0600	Restor	An error occurred installing the privileged helper tool: Error Domain=CFErrorDomainLaunchd Code=8 "(null)"
```
in console. Attached is Console log watching for Restor with "include Debug" turned on.
[restor_log.txt](https://github.com/google/restor/files/2368388/restor_log.txt)

**Comment by russellhancox** [comment]
Is this with a version of Restor you've built yourself? 

Unfortunately the SMJobBless function which installs the helper tool is incredibly picky about signing and contents of certain plists in Restor and embedded in the helper tool itself and the logs it produces are not helpful. The first thing to check is that the designated requirements for both the app and tool are the same and match the respective keys in each Info.plist:

```shell
codesign -d -r- /Applications/Restor.app
codesign -d -r- /Applications/Restor.app/Contents/Library/LaunchServices/com.google.corp.restord
defaults read /Applications/Restor.app/Contents/Info.plist SMPrivilegedExecutables
launchctl plist /Applications/Restor.app/Contents/Library/LaunchServices/com.google.corp.restord | grep -A2 SMAuthorizedClients
```

If you've built the app yourself and these don't match up there might be an issue with the build script that generates them. If you're using a version of Restor we released on the releases page (which definitely has all these things in the right places) then there's something odd going on.

**Comment by WardsParadox** [comment]
It was a version I built myself so I could get access to the disk filtering. I'll double check the signatures.

**Comment by WardsParadox** [comment]
The last command (launchctl plist) doesn't output anything. All the others match our TeamID.

**Comment by russellhancox** [comment]
Odd, that means the Info.plist embedded in the helper tool is missing. I just built Restor fresh on Xcode 9.2 and it was embedded properly. Check the `Build Settings` tab for the `com.google.corp.restord` target to make sure "Create Info.plist section in binary" is set to Yes and the "Info.plist file" path is set.

I'll be uploading a new signed release shortly, so you could also wait for that.

**Comment by WardsParadox** [comment]
I think I'll wait, as I don't know my way around xcode too much other than Interface builder. Thanks for the help :)
