### ISSUE TITLE
'Host' (computer running Restor) powers off during imaging

### ISSUE THREAD

**Issue by arubdesu** [google/restor#53]
Restor Device Model | OS/Build | Restor Version | Image Used | Hardware Being Imaged
------------ | ------------- | ------------ | ------------- | ------------ 
A1989/MBP15,2 | 10.14.2 (18C54) | 1.7(assuming same version priv. helper, sha1 starts 30cf9ffb) | autodmg-cooked 10.14.1 apfs | MBPro escape (A1708, touchbar-less)

Pardon that this is a second-hand report, I'm submitting this on behalf of my techs. ~Will update once they fill me in about the ? points above and/or I'm able to reproduce. I don't have a video of the exact symptom either, can't tell if it's a kernel panic situation, but~ it seems to have occurred on 4 distinct machines, base touchbar current model 13" MBP's and one 15-inch

**Comment by arubdesu** [comment]
I've updated the table in the first comment above with the most recent repro by my coworker, video they provided shows power-off symptom is not a KP, progress bar acts stalled halfway through imaging a disk, unit powers off randomly as if the plug was pulled. No .crash files added to root or user `Library/Logs/DiagnosticReports`, I can't tell if restord.log doesn't just abruptly end, saying it started an imaging session:
```sh
2019-01-08 09:10:01.789 com.google.corp.restord[13205:291502] <ImageSessionServer: 0x7ffb6fc01670> New imaging client: s: 'our-image-10.14.1-18B75.apfs', d: /dev/disk3s2
```

Should I try to build the app with debugging, or is there other suggestions of info to collect/ways to help get to the bottom of this?

**Comment by tburgin** [comment]
Very odd. Are there any previous shutdown codes logged?
`/usr/bin/log show --info --debug --predicate 'message CONTAINS[c] "previous shutdown"'`

Another thought. Maybe the high I/O on the internal SSD is triggering something?  
https://www.apple.com/support/13-inch-macbook-pro-solid-state-drive-service-program/

**Comment by russellhancox** [comment]
Is this still an issue?
