### ISSUE TITLE
asr inverting errors

### ISSUE THREAD

**Issue by ToledoJones** [google/restor#58]
Hi there. First of all, this is a really cool project that I've gotten a tremendous amount of use out of. I'm submitting this on behalf of one of coworkers working in a different office, and honestly I'm not certain if the problem is with our process or Restor. We use custom images I've created with hdiutil. Everyone is using the same images and version of Restor (v1.11 currently). The images are locally stored on mac-mini's in each office location. Lately one of my coworkers has been experiencing some error messages I've never seen before. The first of the issues appeared in v1.8 where one of the techs would receive the following error message during the inverter step of imaging:

<img width="486" alt="Screen Shot1" src="https://user-images.githubusercontent.com/48521404/54285295-ad23c600-456f-11e9-9fc5-27d556ba0b57.png">

Now this is an asr error and not specific to Restor, we tried running asr restore via terminal which kept failing as well. I had the tech attempt from different devices with no avail. Eventually I ended up sending the tech a mac-mini I had tested (in Chicago) to the tech (in NYC). I had confirmed Restor was working on the mac-mini and imaged several brand new 2018 MBPs without any issues. When the tech received the mac-mini, they were able to image one new 2018 MBP successfully, but are now receiving a mixture of errors:

![Screen Shot2](https://user-images.githubusercontent.com/48521404/54285825-b2cddb80-4570-11e9-86ba-a73c70acd79c.png)

Either the error message above will show during the inverter step during imaging or Restor will image and the MBP will boot into the following screen and be unable to start the MBP:

![Image from iOS](https://user-images.githubusercontent.com/48521404/54286316-9b432280-4571-11e9-81c7-0b7ea405127f.jpg)

Our setups are essentially identical, so I'm just curious if anyone has insights or has run into similar issues before. Let me know if more detail is needed, I'll provide what I can. Thanks in advance for any advice anyone can provide.

**Comment by tburgin** [comment]
I have seen similar errors with asr. Most of the time erasing the TDM Mac with diskutil clears things up. Sometimes it is a bad cable. Sometimes imaging multiple machines at the same time tiggers this.  I have also noticed this seems to happen more ofter when using a 15" 2018 MBP as the host machine running Restor.

**Comment by ToledoJones** [comment]
Thanks for the prompt response!

Wiping the TDM Mac was my first thought as well. My coworker has wiped the TDM Macs several times, but the issue is consistently persistent. I had thought about the cable as well, but asr works just fine with non-T2 MBPs. We're also both using 2012 Mac-Mini's (with SSDs) as our host machines running Restor, yet I have no issues imaging NIB T2 MBPs.

I'll have the tech try with a new cable just for fun, but other than that I'm pretty much out of ideas. Thanks for the advice!

**Comment by ToledoJones** [comment]
Update: A new cable didn't make a difference. T2 MBPs still boot with "unable to verify the startup disk". I'll close this since it seems to be a weird asr issue and not particularly relevant to Restor as an application.
