### ISSUE TITLE
How to use a local custom image

### ISSUE THREAD

**Issue by mikaellofgren** [google/restor#6]
Hi
I created a local image .dmg with HighSierra with Autodmg, how to write the plist so Restor will use file instead of URL? My plistfile look like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CustomImage</key>
	<true/>
	<key>Images</key>
	<array>
		<dict>
			<key>Name</key>
			<string>High Sierra (10.13) All Models</string>
			<key>SHA-256</key>
			<string>b0bcd15848c9c4b1a1d8edc6621ce532ffdcafc12d086bf640e4d19dcdb19703</string>
			<key>URL</key>
			<string>/Users/username/Desktop/osx_updated_171010-10.13-17A405.apfs.dmg</string>
		</dict>
	</array>
</dict>
</plist>
```

**Comment by jbaker10** [comment]
@mikaellofgren I would think you would specify the URL with **file:///Users/username/...**, but in a quick test of this, it seems to cause Restor to crash on launch.

That or you could host the image locally using something like the LAMP stack as well.

**Comment by tburgin** [comment]
The easiest way is to:
1. `sudo defaults write /Library/Preferences/com.google.corp.restor.plist CustomImage -bool true`
2. Now you can then just drag and drop an image locally.
![screen shot 2017-10-20 at 10 28 23 am](https://user-images.githubusercontent.com/2117646/31825841-76ad7f5a-b581-11e7-9bef-e907ebccece0.png)

**Comment by mikaellofgren** [comment]
Hi
Its says this when I try to start restor.
<img width="612" alt="skarmavbild 2017-10-20 kl 19 33 16" src="https://user-images.githubusercontent.com/6194908/31834455-4a35b42c-b5ce-11e7-9e34-36fd0e74d572.png">

And plist looks like this. Im running High Sierra.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CustomImage</key>
	<true/>
</dict>
</plist>
```

**Comment by tburgin** [comment]
Yes, you still need a ConfigURL set pointing to a valid config. It doesn't necessarily have to any images defined since you have enabled CustomImage.

**Comment by mikaellofgren** [comment]
Cant get it to work. Does it support https? All my sites use https.

**Comment by tburgin** [comment]
Sorry for the delay, lost track of this thread.
Yes, Restor supports HTTPS only.

Can you paste in your `com.google.corp.restor` preferences and the configuration plist you are using?

**Comment by mikaellofgren** [comment]
Hi! 
I totally missed that I need to have the images.plist hosted on a website and the com.google.corp.restor plist should only point to the images.plist file,
did create a plist to the restor.dmg, cause I only want to use a local .dmg

Shared the images.plist from my dropbox only as a startup configuration.
I noticed that i have to restart the computer to get the settings to work after the changes.

Finally Restor starts but I cant choose a Custom image (local)...never gets the path window.




```shasum -a 256 restor-1.1.dmg```

Then I run this:
```sudo defaults write /Library/Preferences/com.google.corp.restor.plist ConfigURL "https://www.dropbox.com/s/uty68485n4yg7ib/images.plist?dl=1"```

```sudo defaults write /Library/Preferences/com.google.corp.restor.plist CustomImage -bool true```


com.google.restor.plist looks like this:

```<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>ConfigURL</key>
	<string>https://www.dropbox.com/s/uty68485n4yg7ib/images.plist?dl=1</string>
	<key>CustomImage</key>
	<true/>
</dict>
</plist>
```




images.plist looks like this on the web(dropbox):


```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Images</key>
	<array>
		<dict>
			<key>Name</key>
			<string>Restor</string>
			<key>URL</key>
			<string>https://www.dropbox.com/s/okxp8vunvovfoht/restor-1.1.dmg?dl=1</string>
			<key>SHA-256</key>
			<string>4b402a15d4e728f506ed567c7adad9d702e54609ac175cd68ebbcf4f16b10291</string>
		</dict>
	</array>
</dict>
</plist>

```

**Comment by lucascantor** [comment]
@mikaellofgren my guess is the Dropbox `?dl=1` trick in the URL doesn't comply with whatever Restor is expecting.

I've had success storing my `images.plist` file in an [S3 bucket](https://aws.amazon.com/s3/), which you can make public on the Internet, or [whitelist to your corporate IP(s)](https://stackoverflow.com/a/11457790) for example.

**Comment by russellhancox** [comment]
I just tried your configuration on my machine:

```bash
defaults read com.google.corp.restor
{
    ConfigURL = "https://www.dropbox.com/s/uty68485n4yg7ib/images.plist?dl=1";
    CustomImage = 1;
}
```

And opening Restor, I get two _images_ to select: Restor and Custom Image, as expected.

**Comment by mikaellofgren** [comment]
Yes, but can you load a Custom Image then? I can't choose the path to the dmg like this:
https://user-images.githubusercontent.com/2117646/31825841-76ad7f5a-b581-11e7-9bef-e907ebccece0.png

**Comment by russellhancox** [comment]
Yes, I dragged an image onto the "custom Image url" field and began imaging with no issues. Does it give an error?

**Comment by mikaellofgren** [comment]
I Choose Custom Image, and try to drag a .dmg file over restor window. Nothing happens. I don't see the "custom Image url" window. Do I need to have a computer in target mode connected?

**Comment by russellhancox** [comment]
You either need a computer connected, and then the _Custom Image URL_ dialog will appear when you click _Image_ or you can click _Auto-Image_, which will also pop the dialog and will then sit and wait for a new machine to connect and begin imaging immediately.

**Comment by russellhancox** [comment]
Did you manage to get this sorted?

**Comment by mikaellofgren** [comment]
Yes did a quick test now. It worked when I had a computer connected. Thanks!
