### ISSUE TITLE
Restor 1.11 and MacOS 10.14.4

### ISSUE THREAD

**Issue by ryanmoon** [google/restor#61]
Seeing an issue with MacOS 10.14.4, with Restor 1.11 when restoring an image. All target machines boot into a flashing disk upon restor. 
When running MacOS 10.14.3, with Restor 1.11 using the same source images, we see no problems. 
Using `asr` on 10.14.4 works without issue, using this command: `sudo /usr/sbin/asr restore --buffersize 16m --source test.apfs.dmg --target /Volumes/MacHD --erase --noprompt --noverify --puppetstrings --verbose`
Have also tested with Restor 1.8 and have the same issue when running from a 10.14.4 machine.

**Comment by tburgin** [comment]
Try deleting the helper binary when switching Restor versions. Sometimes it doesn't get updated properly.

`sudo rm -rf /Library/PrivilegedHelperTools/com.google.corp.restord`

**Comment by ryanmoon** [comment]
So the initial issue we ran into was this, on 10.14.3 we were running Restor 1.11, and things were working as expected. Then we updated to 10.14.4 (still on Restor 1.11), and we started seeing 0% success when using Restor on 10.14.4. 

Removing the PrivilegedHelperTools sadly does not help, but definitely is a great tip if testing multiple versions of Restor.

Initially I was worried that something drastic had changed with `asr`, but we're able to use `asr` without issue in 10.14.4. 

It appears that there's some sort of apfs conversion issue happening. As when the imaged machine, with the image applied by Restor, boots, it displays the glorious flashing question mark, reconnecting the imaged device to a known good machine via Target Disk Mode, the problem device's hard drive is titled `ASRNewVolume_56838` with a file entitled ContainerToInvert on it. 

If there's any more info I can add, please let me know.

**Comment by ryanmoon** [comment]
For the meantime, we're using Restor on devices running 10.14.3.

**Comment by brandonfriess-stripe** [comment]
Can confirm that we are seeing the same behavior.

What I've noticed is that when Restor finishes, the OS dir structure is present on the target machine.

<img width="981" alt="Screen Shot 2019-04-10 at 4 36 27 PM" src="https://user-images.githubusercontent.com/44347039/55920881-541b7200-5baf-11e9-9478-d0a8c699fe83.png">

But when we power down and then boot the machine for the first time, it essentially loses the directory structure (we also have a volume label of `ASRNewVolume_XXXX`)

<img width="1199" alt="Screen Shot 2019-04-10 at 4 38 19 PM" src="https://user-images.githubusercontent.com/44347039/55920939-8200b680-5baf-11e9-89a6-01bc019a58fb.png">

**Comment by chilcote** [comment]
That PR seems to have fixed the blinking-question-mark issue, on a few tests I just did.

**Comment by brandonfriess-stripe** [comment]
EDIT: I should say that building from master has fixed the blinking-question-mark issue for us as well.

Any chance on a new release?

**Comment by erikng** [comment]
@tburgin any chance you can cut a new version?

**Comment by matt-cahill** [comment]
I'm struggling to build from source using bazel. I'll keep trying but is there any chance of making a new release with this patch?

**Comment by russellhancox** [comment]
I've published a [new release](https://github.com/google/restor/releases/tag/1.15) just now.

**Comment by matt-cahill** [comment]
Much appreciated Russell, thank you.
