### ISSUE TITLE
Build issue due to bazel changes

### ISSUE THREAD

**Issue by arubdesu** [google/restor#67]
As reported in Slack #restor, I was building from source and hitting errors that seem to have been introduced recently in bazel, https://github.com/bazelbuild/bazel/issues/7594
```sh
ERROR: /Users/allister/Documents/restor-master/Restor/BUILD:45:22: in asset_catalogs attribute of objc_library rule //Restor:restor_lib: objc_library resource attributes are not allowed. Please use the 'data' attribute instead.
ERROR: Analysis of target '//Restor:Restor' failed; build aborted: Analysis of target '//Restor:restor_lib' failed; build aborted
INFO: Elapsed time: 65.470s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (38 packages loaded, 654 targets configured)
```
I was able to figure out through the naming of the feature flip that the additional build flag I could use in the meantime is `--incompatible_disable_objc_library_resources=false`
I tried to manually fix it in the BUILD file and it seemed to work for assets but not storyboards, if it had done fixed it you know me brudda, I'dve sent the PR 😉

**Comment by russellhancox** [comment]
Thanks for fixing this (#68)!
