### ISSUE TITLE
Default startup disk

### ISSUE THREAD

**Issue by undaunt** [google/restor#7]
Hello!

I'm currently testing restor with both a local custom image setting as well as downloading over our network off a mac mini with macOS server. Currently the local install of Sierra works, but only if I manually boot into recovery mode and set the hard drive as the startup disk. Else I get the flashing question mark folder boot.

I'm about to test local High Sierra plus network of both versions and will report back further. For reference this was done via TB2 cable off an iMac.

Thanks.

Edit: Network install of Sierra had no issue. I then did a local install of Sierra *again* and the issue did not recur. I'll continue to test with High Sierra on both methods and move on to additional different laptops afterwards.

**Comment by undaunt** [comment]
As a followup, local install of High Sierra deleted the recovery partition from Sierra and installed, but didn't remove the other partition which had been labeled EFI Boot. So I had EFI Boot and Macintosh HD after installing High Sierra. I had to manually select Macintosh HD (High Sierra) and load that to log into 10.13, which worked. Upon reboot, it still defaulted back to thinking the other drive was default.

Next I'll be testing whether removing both partitions manually before kicking off restor will alleviate this and run another network and local install test.

**Comment by tburgin** [comment]
Restor doesn't have much control over the machine in target disk mode. Most likely there is `efi-boot-device` data in the NVRAM telling your machine to boot to a disk that doesn't exist anymore. If you have some sort of management on the newly imaged machine you can try to reset the `efi-boot-device` in NVRAM with this command.

`sudo bless --setBoot --folder /`

**Comment by russellhancox** [comment]
Closing as WAI, as we can't manage the boot device of a machine in target-disk mode, sadly.
