### ISSUE TITLE
http support

### ISSUE THREAD

**Issue by clburlison** [google/restor#9]
Would the Google team accept a PR to enable http support via the `NSAllowsArbitraryLoads` setting?

**Comment by russellhancox** [comment]
Possibly, though I think we'd need convincing; Apple added ATS to encourage everyone to stop using HTTP and (as I'm sure you can understand) we're _very_ much supportive of that direction. 

I suppose we could manage the NSAllowArbitraryLoads setting but then have a configuration option to enforce HTTPS for those of us that would prefer that.

**Comment by clburlison** [comment]
I’m not sure if I can convenience you. I agree with all your points. The only counterpoint is http is very convenient for my home lab.

With that said I doubt restor has many updates as it is pretty feature
complete so I can always maintain a personal copy. Feel free to close.

**Comment by russellhancox** [comment]
Fair enough. I can certainly understand the use for testing but if you're happy maintaining a personal copy for that I'll close. If you (or anyone) wants to re-open in future we'll happily re-evaluate.
